import * as THREE from "three";
const $=s=>document.querySelector(s), scenes=[...document.querySelectorAll(".scene")], progress=$("#progressBar");
let audioEnabled=false,audioCtx=null,warp=0,petalTimer=null;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function showScene(id,step){scenes.forEach(s=>s.classList.toggle("scene--active",s.id===id));progress.style.width=Math.max(8,(step/5)*100)+"%";if(id==="flowerScene"||id==="finale")startPetals();else stopPetals()}
function tone(freq=220,duration=.2,volume=.035){if(!audioEnabled)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(volume,audioCtx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}
function ambience(){[146.83,220,293.66].forEach((f,i)=>setTimeout(()=>tone(f,2.8,.01),i*650))}
$("#soundBtn").onclick=()=>{audioEnabled=!audioEnabled;$("#soundBtn").classList.toggle("sound-on",audioEnabled);$("#soundLabel").textContent=audioEnabled?"Sonido activo":"Sonido";if(audioEnabled){tone(523,.35,.025);ambience()}};
$("#restartBtn").onclick=()=>location.reload();$("#replayBtn").onclick=()=>location.reload();

function makeFlower(el,petals=18){el.innerHTML="";for(let i=0;i<petals;i++){const p=document.createElement("i");p.className="petal"+(i>petals*.58?" inner":"");const ring=i>petals*.58?1:0,angle=(360/petals)*i+(ring?11:0),scale=(ring?.62:.78)+(i%4)*.055;p.dataset.angle=angle;p.dataset.scale=scale;p.style.transform=`rotate(${angle}deg) translate(7px,-50%) scale(${scale}) rotateX(${10+(i%4)*6}deg)`;p.style.zIndex=String(2+(i%5));el.appendChild(p)}const core=document.createElement("i");core.className="core";el.appendChild(core)}
document.querySelectorAll(".flower").forEach((f,i)=>makeFlower(f,i?12:20));
function bloom(){document.querySelectorAll("#mainFlower .petal").forEach((p,i)=>{const a=Number(p.dataset.angle),s=Number(p.dataset.scale);p.animate([{transform:`rotate(${a}deg) translate(1px,-50%) scale(.16) rotateX(65deg)`,opacity:.2},{transform:`rotate(${a}deg) translate(7px,-50%) scale(${s}) rotateX(${10+(i%4)*6}deg)`,opacity:1}],{duration:1500+i*28,easing:"cubic-bezier(.18,.8,.22,1)",fill:"both"})})}

$("#startBtn").onclick=async()=>{audioEnabled=true;$("#soundBtn").classList.add("sound-on");$("#soundLabel").textContent="Sonido activo";tone(392,.5,.025);showScene("countdown",1);const n=$("#countNumber");for(const item of ["3","2","1"]){n.textContent=item;n.animate([{opacity:0,transform:"scale(.58)",filter:"blur(12px)"},{opacity:1,transform:"scale(1)",filter:"blur(0)"},{opacity:0,transform:"scale(1.38)",filter:"blur(8px)"}],{duration:900,easing:"cubic-bezier(.2,.8,.2,1)"});tone(230+Number(item)*55,.18,.024);await wait(900)}n.textContent="✦";tone(659,.8,.03);await wait(650);startJourney()};

async function startJourney(){showScene("journey",2);warp=1;$("#speedLines").style.opacity="1";buildSpeedLines();const phrases=[["Entre millones de luces","A veces una persona llega…"],["Sin avisar","…y hace que algunos días se sientan diferentes."],["Sin darse cuenta","Nos recuerda que todavía existen razones para sonreír."],["Hoy, 21 de septiembre","quise dejarte una pequeña prueba de ello."]];for(const [k,p] of phrases){$("#journeyKicker").textContent=k;$("#journeyPhrase").textContent=p;$("#journeyPhrase").animate([{opacity:0,filter:"blur(16px)",transform:"translateY(28px) scale(.97)"},{opacity:1,filter:"blur(0)",transform:"none"}],{duration:900,fill:"both"});tone(293.66,1.5,.008);await wait(1850)}warp=0;$("#speedLines").style.opacity="0";showScene("flowerScene",3);bloom();ambience()}
function buildSpeedLines(){const box=$("#speedLines");box.innerHTML="";for(let i=0;i<48;i++){const e=document.createElement("i");e.style.transform=`rotate(${i*7.5}deg)`;e.style.animationDelay=`${Math.random()*.72}s`;box.appendChild(e)}}
function startPetals(){stopPetals();const box=$("#petalRain");petalTimer=setInterval(()=>{if(document.hidden)return;const p=document.createElement("i");p.className="falling-petal";p.style.left=Math.random()*100+"vw";p.style.setProperty("--drift",(Math.random()*180-90)+"px");p.style.animationDuration=(5+Math.random()*4)+"s";p.style.transform=`rotate(${Math.random()*180}deg) scale(${.6+Math.random()*.8})`;box.appendChild(p);setTimeout(()=>p.remove(),9500)},window.innerWidth<600?700:420)}
function stopPetals(){clearInterval(petalTimer);petalTimer=null;$("#petalRain").innerHTML=""}
$("#discoverBtn").onclick=()=>{showScene("messages",4);setupMessages()};

const messages=[["Alegría","Que nunca te falten razones para sonreír, incluso en los días que parezcan pequeños."],["Sueños","Que sigas persiguiendo aquello que te emociona, aunque el camino todavía no esté completo."],["Fortaleza","Recuerda todo lo que ya superaste. Eres más fuerte de lo que a veces imaginas."],["Cariño","Que siempre estés rodeada de personas capaces de quererte bonito y con verdad."],["Esperanza","Incluso la noche más larga termina encontrándose con la luz."],["Futuro","Todavía existen muchos momentos increíbles que aún no sabes que van a ocurrir."],["Calma","No tienes que tener todo resuelto hoy. También está bien avanzar despacio."],["Tú","Entre tantas estrellas, ninguna necesita parecerse a otra para poder brillar."]];
let seen=new Set();
function setupMessages(){const box=$("#constellation");if(box.children.length)return;const desktop=[[18,62],[31,48],[47,66],[61,43],[77,58],[70,76],[40,80],[84,34]],mobile=[[14,20],[42,10],[73,22],[23,43],[58,39],[82,49],[38,61],[70,68]],spots=innerWidth<800?mobile:desktop;messages.forEach((m,i)=>{const b=document.createElement("button");b.className="message-node";b.dataset.label=m[0];b.style.left=spots[i][0]+"%";b.style.top=spots[i][1]+"%";b.setAttribute("aria-label","Abrir mensaje: "+m[0]);b.onclick=()=>openMessage(i,b);box.appendChild(b)})}
function openMessage(i,node){seen.add(i);node.classList.add("is-read");$("#messageNumber").textContent=String(i+1).padStart(2,"0");$("#messageTitle").textContent=messages[i][0];$("#messageText").textContent=messages[i][1];$("#messageModal").classList.add("show");tone(440+i*25,.45,.016);if(seen.size>=4)$("#finalBtn").disabled=false}
$("#finalBtn").onclick=()=>{showScene("finale",5);createHeart();tone(523,1.8,.02);setTimeout(()=>tone(659,1.8,.014),420)};
function createHeart(){const box=$("#heartParticles");box.innerHTML="";for(let i=0;i<190;i++){const t=Math.random()*Math.PI*2,x=16*Math.pow(Math.sin(t),3),y=13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t),p=document.createElement("i");p.style.left=(50+x*2.35)+"%";p.style.top=(48-y*2.35)+"%";p.style.animationDelay=Math.random()*2+"s";p.style.transform=`scale(${.5+Math.random()*1.8})`;box.appendChild(p)}}

const canvas=$("#space"),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x05030b,.033);const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,1000);camera.position.z=7;
function starField(count,radius,size,color,opacity=.85){const g=new THREE.BufferGeometry(),p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=Math.pow(Math.random(),.52)*radius,a=Math.random()*Math.PI*2,z=(Math.random()-.5)*radius*1.7;p[i*3]=Math.cos(a)*r;p[i*3+1]=Math.sin(a)*r*.65;p[i*3+2]=z}g.setAttribute("position",new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color,size,transparent:true,opacity,sizeAttenuation:true,depthWrite:false,blending:THREE.AdditiveBlending}))}
const mobile=innerWidth<700,stars=starField(mobile?2300:4200,34,.055,0xe9e0ff,.9),dust=starField(mobile?850:1800,23,.085,0xff9fc9,.58),blue=starField(mobile?600:1100,27,.075,0x8292ff,.55);scene.add(stars,dust,blue);
const nebulaGroup=new THREE.Group();for(let i=0;i<5;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(6+i*1.5,32,32),new THREE.MeshBasicMaterial({color:[0x44195d,0x1c315f,0x5b173f][i%3],transparent:true,opacity:.018+(i%2)*.012,side:THREE.BackSide,blending:THREE.AdditiveBlending}));m.position.set((i-2)*1.8,Math.sin(i)*1.4,-i*.6);m.scale.y=.72+i*.05;nebulaGroup.add(m)}scene.add(nebulaGroup);
let mx=0,my=0;addEventListener("pointermove",e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5},{passive:true});addEventListener("deviceorientation",e=>{if(e.gamma!=null){mx=Math.max(-.5,Math.min(.5,e.gamma/90));my=Math.max(-.5,Math.min(.5,(e.beta-40)/100))}},{passive:true});
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:2));renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function render(now){const dt=Math.min((now-last)/1000,.04);last=now;stars.rotation.z+=dt*.008;dust.rotation.z-=dt*.013;blue.rotation.y+=dt*.007;nebulaGroup.rotation.z+=dt*.002;camera.position.x+=(mx*.65-camera.position.x)*.025;camera.position.y+=(-my*.42-camera.position.y)*.025;camera.position.z+=((warp?1.6:7)-camera.position.z)*.034;stars.position.z+=warp?dt*9:dt*.07;if(stars.position.z>10)stars.position.z=0;dust.position.z+=warp?dt*5.5:0;if(dust.position.z>8)dust.position.z=0;renderer.render(scene,camera);requestAnimationFrame(render)}requestAnimationFrame(render);
